# Generated by Django 5.2 on 2025-10-18 05:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Gramin Health Shield', max_length=100)),
                ('product_type', models.CharField(choices=[('HEALTH', 'Health Insurance'), ('LIFE', 'Life Insurance'), ('VEHICLE', 'Vehicle Insurance'), ('CROP', 'Crop Insurance'), ('PROPERTY', 'Property/Home Insurance'), ('LIVESTOCK', 'Livestock Insurance')], max_length=20)),
                ('description', models.TextField(help_text='A simple, detailed description of what this insurance covers.')),
                ('key_features', models.TextField(help_text='List key features, separated by newlines for easy display.')),
                ('base_premium', models.DecimalField(decimal_places=2, help_text='Starting premium amount.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is this product currently offered?')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_assured', models.DecimalField(decimal_places=2, help_text='The total coverage amount.', max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING_APPROVAL', 'Pending Approval')], default='PENDING_APPROVAL', max_length=20)),
                ('product', models.ForeignKey(help_text='The type of product this policy is based on.', on_delete=django.db.models.deletion.PROTECT, to='insurance.insuranceproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='Detailed description of the incident for the claim.')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('FILED', 'Filed'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='FILED', max_length=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Full address for communication', max_length=255)),
                ('phone_number', models.CharField(help_text='10-digit mobile number', max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
