# Generated by Django 5.2.7 on 2025-10-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('HEALTH', 'Health Insurance'), ('LIFE', 'Life Insurance'), ('VEHICLE', 'Vehicle Insurance'), ('CROP', 'Crop Insurance'), ('PROPERTY', 'Property/Home Insurance'), ('LIVESTOCK', 'Livestock Insurance')], max_length=20)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed explanation of what the user needs to do for this step.')),
            ],
            options={
                'ordering': ['product_type', 'step_number'],
            },
        ),
    ]
