# Generated by Django 5.2.8 on 2026-01-31 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_claimstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='pincode',
            field=models.CharField(default='000000', help_text='Used to show agents near user', max_length=6),
        ),
        migrations.AddField(
            model_name='agent',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for staff'),
        ),
        migrations.AddField(
            model_name='claim',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Upload bills, photos, or FIR copy', null=True, upload_to='claim_evidence/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='incident_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when the incident/illness occurred'),
        ),
        migrations.AddField(
            model_name='claim',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if claim is rejected', null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Claims, Payments, General', max_length=50),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='benefits_structure',
            field=models.JSONField(blank=True, default=dict, help_text="JSON Data: e.g. {'room_rent': '1%', 'icu': '2%'}"),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='brochure',
            field=models.FileField(blank=True, help_text='Official PDF Brochure', null=True, upload_to='brochures/'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='max_entry_age',
            field=models.PositiveIntegerField(default=65),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='min_entry_age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='policy',
            name='next_payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='nominee_age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='policy',
            name='nominee_name',
            field=models.CharField(default='Pending', help_text='Full name of nominee', max_length=100),
        ),
        migrations.AddField(
            model_name='policy',
            name='nominee_relation',
            field=models.CharField(default='Other', help_text='Relation to policy holder', max_length=50),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_document',
            field=models.FileField(blank=True, help_text='The generated policy PDF', null=True, upload_to='policy_docs/'),
        ),
        migrations.AddField(
            model_name='policy',
            name='premium_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='YEARLY', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_kyc_verified',
            field=models.BooleanField(default=False, help_text="Has the admin verified this user's documents?"),
        ),
        migrations.AddField(
            model_name='profile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(blank=True, default='000000', help_text='Crucial for matching with local agents', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Full content of the article.'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(help_text='Detailed description of the incident.'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('FILED', 'Filed'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLED', 'Payment Settled')], default='FILED', max_length=20),
        ),
        migrations.AlterField(
            model_name='claimstep',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='description',
            field=models.TextField(help_text='A detailed description of coverage.'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='key_features',
            field=models.TextField(help_text='List key features separated by newlines.'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.insuranceproduct'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING_APPROVAL', 'Pending Approval'), ('LAPSED', 'Lapsed (Payment Missed)')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='sum_assured',
            field=models.DecimalField(decimal_places=2, help_text='Total coverage amount.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, help_text='Full address for communication', null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Credit/Debit Card'), ('NETBANKING', 'Net Banking')], max_length=50)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='insurance.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('DL', 'Driving License'), ('MEDICAL', 'Medical Report'), ('RC', 'Vehicle RC Book'), ('OTHER', 'Other')], max_length=50)),
                ('title', models.CharField(help_text="e.g., 'My Blood Test Report'", max_length=100)),
                ('file', models.FileField(upload_to='user_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
