# Generated by Django 5.2.8 on 2026-01-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_agent_pincode_agent_state_claim_admin_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='policy',
        ),
        migrations.DeleteModel(
            name='ClaimStep',
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
