# Generated by Django 5.2.8 on 2026-01-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_remove_claim_policy_delete_claimstep_delete_claim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='base_premium',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='benefits_structure',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='key_features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='policy',
            name='nominee_name',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='policy',
            name='nominee_relation',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_document',
            field=models.FileField(blank=True, null=True, upload_to='policy_docs/'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='sum_assured',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
