# Generated by Django 5.2.8 on 2026-02-02 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_delete_agent_alter_article_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='product_icons/'),
        ),
        migrations.CreateModel(
            name='AgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('preferred_language', models.CharField(default='English', max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insuranceproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('te', 'Telugu'), ('ta', 'Tamil'), ('gu', 'Gujarati'), ('kn', 'Kannada')], max_length=5)),
                ('translated_description', models.TextField()),
                ('translated_key_features', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='insurance.insuranceproduct')),
            ],
            options={
                'unique_together': {('product', 'language')},
            },
        ),
    ]
