# Generated by Django 5.2.8 on 2026-01-31 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0006_agent_pincode_agent_state_claim_admin_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('step_number', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FILED', 'Filed'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='FILED', max_length=20)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='claims/evidence/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='claims/audio/')),
                ('description', models.TextField(blank=True, help_text='Auto-transcribed from audio')),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.policy')),
            ],
        ),
    ]
