# Generated by Django 5.2.8 on 2026-01-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        ('insurance', '0007_remove_claim_policy_delete_claimstep_delete_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='audio_file',
        ),
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(blank=True, help_text='Describe incident details'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='evidence_image',
            field=models.ImageField(default='', help_text='Upload a photo of the incident', upload_to='claims/evidence/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.policy'),
        ),
    ]
