# Generated by Django 5.2.8 on 2026-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='state',
        ),
        migrations.AddField(
            model_name='agent',
            name='experience_years',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='languages',
            field=models.CharField(default='English', help_text='Comma separated (e.g., Hindi, Marathi)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.CharField(default='Pune', help_text='City or District (e.g., Pune)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(default='agent_photos/default_agent.png', upload_to='agent_photos/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
    ]
