# Generated by Django 5.2.8 on 2026-02-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_agent_address_remove_agent_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='specialization',
            field=models.CharField(default='General Insurance', help_text='Main expertise (e.g. Crop, Health)', max_length=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='state',
            field=models.CharField(default='Maharashtra', help_text='State (e.g. Maharashtra)', max_length=50),
        ),
    ]
